@startuml
'https://plantuml.com/class-diagram


interface Weapon{
void kill();
Stirng getName();
int getType();
}

class Trancsformer{
    Weapon w;
    void attack();
}
Trancsformer o- Weapon
class q{
void kill();
Stirng getName();
int getType();
}
class j{
void kill();
Stirng getName();
int getType();
}
class ytj{
void kill();
Stirng getName();
int getType();
}
Weapon <|... ak47
@enduml