@startuml
'https://plantuml.com/class-diagram

Point <|-Point3d

class Point{
int x;
int y;
+ String toString();
+ double distance();
}
class Point3d{
int z;
+ String toString();
+ double distance();
}

@enduml



