@startuml
'https://plantuml.com/class-diagram

Shape <|-- Circle
Shape <|-- Squire
Shape <|-- Line
class Shape{

+void draw();
+void clear();
}w

class Circle{
void clear1();
}

class Squire{}
class Line{}

@enduml